version: '3.7'

services:
  node:
    env_file:
      - .env
    build:
      context: .
      target: development
      args:
        - NODE_IMAGE
    user: node
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    command: sh -c "yarn install && yarn start:dev"
    networks:
      - default

networks:
  default:
